apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    purpose: observability-backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    purpose: kafka-hbase-data-plane
